const {spawn} = require('node:child_process');
const fs = require('node:fs');
const assert = require('node:assert/strict');
// Run against tests/retirement_demo.py --state funded --port 5187. Synthetic data only.
const dir = fs.mkdtempSync('/tmp/lt-scenario-chrome-');
const chrome = spawn('/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', ['--headless=new','--disable-gpu','--no-first-run','--disable-background-networking','--disable-component-update','--no-default-browser-check','--remote-debugging-port=9337',`--user-data-dir=${dir}`,'about:blank'], {stdio:'ignore'});
const delay = ms => new Promise(r=>setTimeout(r,ms));
(async()=>{
 let targets;
 for(let i=0;i<60;i++){try {targets=await (await fetch('http://127.0.0.1:9337/json/list')).json();break;}catch{await delay(150);}}
 const ws = new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);
 await new Promise(r=>ws.addEventListener('open',r,{once:true}));
 let id=0;const pending=new Map();
 ws.addEventListener('message',e=>{const msg=JSON.parse(e.data);if(msg.id){const p=pending.get(msg.id);pending.delete(msg.id);msg.error?p.reject(msg.error):p.resolve(msg.result);}});
 const call=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});
 const evaluate=async expression=>(await call('Runtime.evaluate',{expression,returnByValue:true})).result.value;
 const key=async k=>{await call('Input.dispatchKeyEvent',{type:'rawKeyDown',key:k,code:k,windowsVirtualKeyCode:k==='Tab'?9:13});if(k==='Enter') await call('Input.dispatchKeyEvent',{type:'char',text:'\r',unmodifiedText:'\r',key:'Enter',windowsVirtualKeyCode:13});await call('Input.dispatchKeyEvent',{type:'keyUp',key:k,code:k,windowsVirtualKeyCode:k==='Tab'?9:13});};
 const navigate=async url=>{await call('Page.navigate',{url});await delay(350);};
 await call('Page.enable');await call('Runtime.enable');
 await call('Emulation.setDeviceMetricsOverride',{width:1400,height:1000,deviceScaleFactor:1,mobile:false});

 await navigate('http://127.0.0.1:5187/retirement/scenarios');
 assert.equal(await evaluate("document.querySelectorAll('.rp-grid input').length"),4);
 await evaluate("document.getElementById('name').value = 'Integration regression'");
 const fillRow = async (index, values) => evaluate(`(() => {const inputs=[...document.querySelectorAll('.rp-grid input')].slice(${index*4},${index*4+4}); ${JSON.stringify(values)}.forEach((v,i)=>{inputs[i].value=v; inputs[i].dispatchEvent(new Event('input',{bubbles:true}));});})()`);
 await fillRow(0,['-30','-5','0','-10']);
 await evaluate("document.querySelector('.rp-add').focus()");await key('Enter');
 assert.equal(await evaluate("document.querySelectorAll('.rp-grid input').length"),8);
 await evaluate("document.querySelector('.rp-add').click()");
 await fillRow(2,['10','3','1','5']);
 assert.equal(await evaluate("document.querySelector('textarea').value"),'-30,-5,0,-10\n,,,\n10,3,1,5');
 await evaluate("document.getElementById('save_comparison').focus()");await key('Enter');await delay(500);
 assert.match(await evaluate('location.pathname'),/\/retirement\/scenarios$/);
 assert.match(await evaluate('document.body.innerText'),/Row 2:/);
 assert.equal(await evaluate("document.querySelectorAll('.rp-grid input').length"),12);
 assert.equal(await evaluate('document.activeElement.id'),'return_path');
 assert.equal(await evaluate("document.querySelector('textarea').value"),'-30,-5,0,-10\n,,,\n10,3,1,5');
 // Removing the original first row must transfer the label and error target.
 await evaluate("document.querySelector('.rp-remove').focus()");await key('Enter');
 assert.equal(await evaluate("document.querySelectorAll('#return_path').length"),1);
 assert.equal(await evaluate("document.querySelector('label[for=return_path]').control === document.querySelector('.rp-grid input')"),true);
 assert.equal(await evaluate('document.activeElement.id'),'return_path');
 assert.equal(await evaluate("document.getElementById('return_path').getAttribute('aria-invalid')"),'true');
 assert.match(await evaluate("document.getElementById('return_path').getAttribute('aria-describedby')"),/return_path-error/);
 assert.equal(await evaluate("document.querySelector('textarea').value"),',,,\n10,3,1,5');
 await fillRow(0,['-30','-5','0','-10']);
 await evaluate("document.querySelector('.rp-add').click()");
 assert.equal(await evaluate("document.querySelector('textarea').value"),'-30,-5,0,-10\n10,3,1,5');
 await evaluate("document.getElementById('save_comparison').focus()");await key('Enter');await delay(700);
 const integratedUrl=await evaluate('location.href');
 assert.match(integratedUrl,/\/retirement\/scenarios\/\d+/);
 assert.equal(await evaluate("document.querySelectorAll('tr.entered-year').length"),2);
 assert.equal(await evaluate(`(() => {
   const el=document.querySelector('[data-chart="scenario-ending"]');
   const lists=[JSON.parse(el.dataset.baseline),JSON.parse(el.dataset.stress)];
   const tables=[...document.querySelectorAll('table.path-table')];
   return lists.every((values,i)=>values.every((v,j)=>v===Number(tables[i].tBodies[0].rows[j].lastElementChild.innerText.replace(/[^0-9.-]/g,''))));
 })()`),true);
 await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
 await navigate(integratedUrl);
 assert.equal(await evaluate(`(() => {const c=document.querySelector('canvas');const ctx=c.getContext('2d');return ctx.getImageData(0,0,c.width,c.height).data.some((v,i)=>i%4===3&&v>0);})()`),true);
 fs.writeFileSync('/tmp/lt-scenario-integration.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await call('Emulation.setScriptExecutionDisabled',{value:true});
 await navigate('http://127.0.0.1:5187/retirement/scenarios');
 await evaluate("document.getElementById('name').focus()");
 await call('Input.insertText',{text:'Early downturn — browser fixture'});
 await evaluate("document.getElementById('return_path').focus()");
 await call('Input.insertText',{text:'-30, -5, NaN, -10'});
 await key('Tab');assert.equal(await evaluate('document.activeElement.id'),'save_comparison');await key('Enter');await delay(500);
 assert.equal(await evaluate('document.activeElement.id'),'return_path');
 assert.match(await evaluate('document.body.innerText'),/Row 1:/);
 assert.equal(await evaluate("document.getElementById('name').value"),'Early downturn — browser fixture');
 await evaluate("document.getElementById('return_path').select()");
 await call('Input.insertText',{text:'-30,-5,0,-10\n10,3,1,5'});
 await key('Tab');await key('Enter');await delay(700);
 assert.match(await evaluate('location.pathname'),/\/retirement\/scenarios\/\d+/);
 assert.match(await evaluate('document.body.innerText'),/Baseline annual path/);
 assert.equal(await evaluate("document.querySelectorAll('h1').length"),1);
 const savedUrl=await evaluate('location.href');
 fs.writeFileSync('/tmp/lt-scenario-desktop.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await evaluate("document.querySelector('main details summary').focus()");await key('Enter');
 assert.equal(await evaluate("document.querySelector('main details').open"),true);
 await call('Emulation.setDeviceMetricsOverride',{width:480,height:1000,deviceScaleFactor:1,mobile:false});
 await call('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
 await navigate(savedUrl);
 assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'),true);
 fs.writeFileSync('/tmp/lt-scenario-narrow.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await navigate('http://127.0.0.1:5187/retirement/scenarios');
 assert.equal(await evaluate('document.documentElement.scrollWidth <= innerWidth'),true);
 fs.writeFileSync('/tmp/lt-scenario-form.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await call('Emulation.setScriptExecutionDisabled',{value:false});await navigate(savedUrl);
 assert.match(await evaluate('document.body.innerText'),/Early downturn/);
 console.log(JSON.stringify({editorRegressions:'blank middle year rejected, first-row removal preserves label/error target, trailing blanks ignored',chart:'painted with reduced motion; all points match annual table values',savedUrl,noJavaScript:'keyboard save and first-error recovery passed',narrow:'480px no page overflow',reducedMotion:'static results',screenshots:['/tmp/lt-scenario-desktop.png','/tmp/lt-scenario-narrow.png','/tmp/lt-scenario-form.png']}));
 ws.close();
})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>{chrome.kill();});
