"""Add current positions and values

Revision ID: 4bf251d2fc42
Revises: f330c5030c4b
Create Date: 2026-08-02 22:00:58.104974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf251d2fc42'
down_revision = 'f330c5030c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('base_currency_code', sa.String(length=3), nullable=False),
    sa.Column('quote_currency_code', sa.String(length=3), nullable=False),
    sa.Column('quote_per_base_amount', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('base_currency_code <> quote_currency_code', name='fx_currencies_differ'),
    sa.CheckConstraint('quote_per_base_amount > 0', name='fx_rate_positive'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fx_rates')),
    sa.UniqueConstraint('base_currency_code', 'quote_currency_code', 'effective_date', name='uq_fx_pair_date')
    )
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fx_rates_effective_date'), ['effective_date'], unique=False)

    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ticker_or_isin', sa.String(length=64), nullable=True),
    sa.Column('instrument_type', sa.String(length=32), nullable=False),
    sa.Column('valuation_currency_code', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("instrument_type IN ('cash','fund','etf','stock','bond','government_savings','fixed_deposit','money_market','other')", name='instrument_type_supported'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_instruments_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments'))
    )
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instruments_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=40), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='posted', nullable=False),
    sa.Column('reverses_transaction_id', sa.Integer(), nullable=True),
    sa.Column('activity_group_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('posted','reversed')", name='transaction_status_supported'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_transactions_portfolio_id_portfolios')),
    sa.ForeignKeyConstraint(['reverses_transaction_id'], ['transactions.id'], name=op.f('fk_transactions_reverses_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('price_amount > 0', name='price_amount_positive'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_prices_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prices')),
    sa.UniqueConstraint('instrument_id', 'effective_date', name='uq_price_instrument_date')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prices_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('position_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('tracking_mode', sa.String(length=32), nullable=False),
    sa.Column('opening_date', sa.Date(), nullable=True),
    sa.Column('closing_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("tracking_mode IN ('transaction_tracked','statement_valued')", name='tracking_mode_supported'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_position_registrations_account_id_accounts')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_position_registrations_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_position_registrations')),
    sa.UniqueConstraint('account_id', 'instrument_id', name='uq_registration_account_instrument')
    )
    with op.batch_alter_table('position_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_registrations_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_registrations_instrument_id'), ['instrument_id'], unique=False)

    op.create_table('postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('posting_kind', sa.String(length=20), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('quantity_delta', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('cash_amount_delta', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('price_currency_code', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("posting_kind IN ('instrument','cash','income','expense','clearing')", name='posting_kind_supported'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_postings_account_id_accounts')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_postings_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_postings_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postings'))
    )
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_postings_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postings_instrument_id'), ['instrument_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_postings_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('valuation_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_registration_id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('native_value_amount', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('native_value_amount >= 0', name='native_value_nonnegative'),
    sa.ForeignKeyConstraint(['position_registration_id'], ['position_registrations.id'], name=op.f('fk_valuation_observations_position_registration_id_position_registrations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_valuation_observations')),
    sa.UniqueConstraint('position_registration_id', 'effective_date', name='uq_observation_registration_date')
    )
    with op.batch_alter_table('valuation_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuation_observations_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_valuation_observations_position_registration_id'), ['position_registration_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valuation_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuation_observations_position_registration_id'))
        batch_op.drop_index(batch_op.f('ix_valuation_observations_effective_date'))

    op.drop_table('valuation_observations')
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_postings_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_postings_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_postings_account_id'))

    op.drop_table('postings')
    with op.batch_alter_table('position_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_registrations_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_position_registrations_account_id'))

    op.drop_table('position_registrations')
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prices_instrument_id'))
        batch_op.drop_index(batch_op.f('ix_prices_effective_date'))

    op.drop_table('prices')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_effective_date'))

    op.drop_table('transactions')
    with op.batch_alter_table('instruments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instruments_portfolio_id'))

    op.drop_table('instruments')
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fx_rates_effective_date'))

    op.drop_table('fx_rates')
    # ### end Alembic commands ###
